# Weather Data - uses Dark Sky API
weatherLocation: <string|location>
latitude: <float|lat>
longitude: <float|lon>
DarkSkyApiKey: <string|apiKey>

# Hacker News
HackerNewsPostCount: <int|n>

# Anime
MALUsername: <string|username>

# List of RSS Feeds
feeds:
  - title: <string|title>,
    link: <string|url>
  # ...

# disks - NOTE: THIS IS AN UBUNTU-ONLY FEATURE AT THE MOMENT
disks:
  - <string|disk-location>
  # ...


Debug: <bool|b>