# Weather Data - uses Dark Sky API
weatherLocation: <string|location>
latitude: <float|lat>
longitude: <float|lon>
DarkSkyApiKey: <string|apiKey>

# Hacker News
HackerNewsPostCount: <int|n>

# Anime
MALUsername: <string|username>

# List of RSS Feeds
feeds:
  - title: <string|title>,
    link: <string|url>

Debug: <bool|b>